### ISSUE TITLE
Documentation for setup and installation

### ISSUE THREAD

**Issue by haklop** [haklop/myqapp#16]
- Add an entry on the wiki
- Create a script for setup mongodb

**Comment by edralzar** [comment]
les points ou j'ai eu du mal en récupérant le projet / à bien lister dans la doc : 
- il faut lancer une instance de mongodb
- il faut que le port 8080 soit libre, et ne pas changer pour un autre port (sans quoi le callback oauth de google sera refusé)
- il faut créer un utilisateur correspondant au login google (?) dans mongodb
- go jetty:run go!
